### ISSUE TITLE
ALL / EN - Captions images en bas de page

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#10]
Hello @WamiConcept 
Voici les légendes des 3 images à intégrer en bas de page (nous recevrons les contenus photos cette semaine), vous pouvez déjà intégrer les légendes en attendant !
Il faut mettre un style gras pour les titres. 

**Year in, year out** 
Filled in 1999 and disgorged in 2019, when Ardbeg Traigh Bhan finally left the cask, it was a said to be the most amazing aroma the Distillery had ever smelt. To experience it for yourself, simply uncork a bottle of your own…

**Splash the mash**
In 1999 – when Ardbeg Traigh Bhan’s journey began – the Ardbeg Distillery installed a brand spanking new mashtun. This is the same mashtun that has helped create so many more incredible Ardbegs over the years. 

**Not aged one bit (Dugga, that is)**
Dugga, Ardbeg’s Head Warehouseman, was at the Distillery from start to finish for Ardbeg Traigh Bhan’s maturation. But unlike this whisky, he’s not aged at all.

**Comment by WamiConcept** [comment]
C'est fait

**Comment by marieharder** [comment]
oki mais il faudrait faire un retour à la ligne un peu moins loin, comme ce que je vous momntrais sur la capture ci-dessous :)
@wamiconcept

<img width="655" alt="Capture d’écran 2019-08-28 à 13 23 36" src="https://user-images.githubusercontent.com/37293165/63851893-5f710d80-c997-11e9-99d7-77aada97bf8c.png">

**Comment by WamiConcept** [comment]
#11
