### ISSUE TITLE
ALL / DE - Captions images en bas de page

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#11]
Et la version allemande :) 
@WamiConcept 

**Jahr ein, Jahr aus**
Als Ardbeg Traigh Bhan 1999 abgefüllt und 2019 das Fass verließ, war es das ungewöhnlichste Aroma, das in der Destillerie jemals gerochen wurde. Um es nachzuvollziehen, entkorken Sie doch einfach eine eigene Flasche…

**Splash the Mash**
1999 - als die Reise von Ardbeg Traigh Bhan begann - installierte die Ardbeg Destillerie einen brandneuen Maischebottich. Dieser Maischebottich hat im Laufe der Jahre dazu beigetragen, viele weitere unglaubliche Ardbeg Abfüllungen zu erschaffen.

**Kein bisschen gealtert (das ist Dugga)**
Dugga, Ardbegs Chef-Warehouse-Man, war vom Anfang an in der Destillerie, um die Reifung von Ardbeg Traigh Bhan zu überwachen. Aber im Gegensatz zu diesem Whisky ist er überhaupt nicht gereift...

**Comment by marieharder** [comment]
@WamiConcept 
Sur desktop les captions apparaissent un peu proches les unes des autres 
est ce qu'on peut faire le retour à la ligne un peu avant ? 

<img width="1232" alt="Capture d’écran 2019-08-27 à 11 31 50" src="https://user-images.githubusercontent.com/37293165/63759777-6415c300-c8be-11e9-9137-4ad6bdd3d6b9.png">

**Comment by WamiConcept** [comment]
En place
