### ISSUE TITLE
MOBILE - iPhone 7 - Safari 11.3 + Chrome 76  / éléments décalés

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#12]
Hello @WamiConcept 
Certains éléments apparaissent en décalé sur la page :
- la ligne avec les batch codes
- les tasting notes

![IMG_1138](https://user-images.githubusercontent.com/37293165/63758981-fddc7080-c8bc-11e9-9b2e-d7fe6eb6b778.PNG)
![IMG_1137](https://user-images.githubusercontent.com/37293165/63758991-02088e00-c8bd-11e9-80fd-94bb7b146eea.PNG)

**Comment by enzo-wami** [comment]
@marieharder C'est corrigé
