### ISSUE TITLE
MOBILE - iPhone 7 - Safari 11.3 + Chrome 76 / Page non fixe mouvement droite / gauche

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#13]
Hello @WamiConcept 
Quand je swipe à droite / gauche sur la page, elle n'est pas fixe, elle bouge et on voit donc du gris sur les côtés 

![IMG_1140](https://user-images.githubusercontent.com/37293165/63759170-590e6300-c8bd-11e9-99f9-86f03f4e3e01.PNG)

**Comment by WamiConcept** [comment]
Corrigé
