### ISSUE TITLE
MOBILE - iPhone 7 - Safari 11.3 + Chrome 76 / Carrousel contenus bas de page

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#14]
Hello @WamiConcept 
Il faudrait mettre juste 3 contenus dans le carrousel en bas de page 
+ enlever les flèches qui apparaissent en dessous des contenus 
+ question : sur desktop les visuels sont carré, il les faudrait aussi carré sur mobile du coup sinon on va devoir mettre 2 assets différents ?
+ quand je change de contenu au swipe, la page bouge 

![IMG_1140](https://user-images.githubusercontent.com/37293165/63759336-9a9f0e00-c8bd-11e9-8683-30b110412f1d.PNG)

**Comment by WamiConcept** [comment]
Corrigé

**Comment by marieharder** [comment]
Merci ! 
@WamiConcept est ce que tu peux désactiver le fait que le carrousel tourne en boucle stp sur mobile ?

**Comment by enzo-wami** [comment]
C'est fait
