### ISSUE TITLE
MOBILE - iPhone 7 - Safari 11.3 + Chrome 76 / Bouton buy now

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#15]
Coucou @WamiConcept 
Le texte "buy now" dans le bouton est décalé, il faudrait que ca soit centré (comme sur la créa je pense)

![IMG_1139](https://user-images.githubusercontent.com/37293165/63759511-eb166b80-c8bd-11e9-9364-4206a5dde9cf.PNG)

**Comment by enzo-wami** [comment]
@marieharder c'est corrigé

**Comment by marieharder** [comment]
cool merci
