### ISSUE TITLE
ALL - Desktop / Batch code section

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#17]
Hello @WamiConcept 
Le carton batch code n'est pas justifié sur le reste des éléments, il est légèrement décalé. 
Il faudrait que tout soit ferré sur la même ligne à gauche comme sur la création !

En préprod : 
<img width="796" alt="Capture d’écran 2019-08-27 à 11 39 17" src="https://user-images.githubusercontent.com/37293165/63760321-6593bb00-c8bf-11e9-8fbd-36c651dc9207.png">

Sur la créa : 
<img width="627" alt="Capture d’écran 2019-08-27 à 11 36 06" src="https://user-images.githubusercontent.com/37293165/63760350-72181380-c8bf-11e9-840b-bb53b648fb7c.png">

**Comment by enzo-wami** [comment]
@marieharder C'est corrigé !

**Comment by marieharder** [comment]
top !
