### ISSUE TITLE
MOBILE - iPhone 7 - Safari 11.3 + Chrome 76 / Légende otarie

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#18]
Hello @WamiConcept 
La légende sous l'otarie apparaît trop proche du titre "Especially rare" 
Il faudrait la rapprocher plus de l'otarie + diminuer l'interlignage entre les 2 lignes de la légende. 

![IMG_1141](https://user-images.githubusercontent.com/37293165/63761445-747b6d00-c8c1-11e9-9367-3e82cb8e8b26.PNG)

**Comment by enzo-wami** [comment]
C'est corrigé

**Comment by marieharder** [comment]
je ne le vois pas en pp tu peux repush ? @enzo-wami @WamiConcept

**Comment by enzo-wami** [comment]
En effet la modif n'était pas passée, c'est bon maintenant
