### ISSUE TITLE
DESKTOP - PC - Firefox 68 + Chrome / Contenus bas de page

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#19]
Hello @WamiConcept 
En bas de page, les 3 contenus en bas de page ont été étirés. 
Il faudrait qu'ils soient carré en toutes circonstances comme sur la créa ci-dessous. 

<img width="1106" alt="Capture d’écran 2019-08-27 à 12 02 05" src="https://user-images.githubusercontent.com/37293165/63762116-91fd0680-c8c2-11e9-9ae0-ab9f33d0a739.png">

**Comment by WamiConcept** [comment]
C'est ok

**Comment by marieharder** [comment]
je ne le vois pas en pp :/
@wamiconcept
