### ISSUE TITLE
MOBILE - Tasting notes

### ISSUE THREAD

**Issue by matildeq** [matildeq/Ardbeg---Traigh-Bhan#2]
Hello @antoinesimonwami 
Nous avons remarqué 2 choses sur cette section en mobile : 
1. il manque un petit plus sur le chocolat
2. quand on clique sur le plus il y a un petit flash pas super sympa au niveau de l'apparition du texte, comme si toute la zone clickable se mettait en highlight. 

Dis-moi si t'as besoin de plus de détails ,
Merci,
Matilde

**Comment by antoinesimonwami** [comment]
C'est corrigé en preprod !

**Comment by matildeq** [comment]
Hello, 
C'est bon pour moi ! Merci !

**Comment by marieharder** [comment]
Hello @antoinesimonwami 
Quand je clique sur le chocolat la description est trop longue et le mot "chocolate" est coupé du coup. je pense qu'il faudrait le passer sur 2 lignes ?

**Comment by antoinesimonwami** [comment]
Plus de précision sur le problème :) ? Quel OS / navigateur?

**Comment by marieharder** [comment]
Oui sorry je suis sur iPhone 7 / Safari / OS 11.3.1
@antoinesimonwami

**Comment by antoinesimonwami** [comment]
C'est bon, corrigé en preprod :)

**Comment by matildeq** [comment]
C'est good merci !
