### ISSUE TITLE
ALL - EN / Texte en double

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#21]
Hello @WamiConcept 
Le texte 
"The epitome of an aged Ardbeg – matured in American oak and Oloroso sherry casks – Ardbeg Traigh Bhan effortlessly accomplishes… the impossible balance." apparaît deux fois sur la page EN. Il s'agit du 3ème paragraphe sur la page.

**Comment by WamiConcept** [comment]
@marieharder On a 4 paragraphes en allemand, je pense que c'était pour prévoir de la place pour ce qui manquait sur la version anglaise. Tu as ce texte ?
"Ein Verkostungsvideo mit Mickey Heads, Destillerie Manager. "

**Comment by marieharder** [comment]
alors nope il faut bien retirer le 4ème paragraphe sur la version EN
et sur la version DE il faut supprimer cette phrase "Ein Verkostungsvideo mit Mickey Heads, Destillerie Manager. "
@WamiConcept

**Comment by WamiConcept** [comment]
C'est ok
