### ISSUE TITLE
MOBILE - Samsung S10 - tasting notes

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#23]
Hello @WamiConcept 
Quand je clique sur les "+" sur le citron et le chocolat les textes s'affichent sur les tasting notes. Possible de décaler un peu les + pour que le texte ne morde pas sur la tasting note ?

![Screenshot_20190827-122951_Chrome](https://user-images.githubusercontent.com/37293165/63764626-86600e80-c8c7-11e9-85a4-767ebcc7c299.jpg)

**Comment by WamiConcept** [comment]
Corrigé
