### ISSUE TITLE
ALL - MOBILE / Bouton Join the committee

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#24]
Hello @WamiConcept 
Sur mobile, le bouton "Join the Committee" doit être de la même largeur que le reste des contenus. Actuellement il est plus large :)

![Screenshot_20190827-123128_Chrome](https://user-images.githubusercontent.com/37293165/63764982-5cf3b280-c8c8-11e9-92e0-e4fb40f28e3a.jpg)

**Comment by enzo-wami** [comment]
@marieharder C'est corrigé
