### ISSUE TITLE
ALL / Contenus bas de page

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#26]
Hello @WamiConcept 
Voici en PJ les 3 contenus à mettre en bas de page !
https://drive.google.com/drive/folders/1SFion2Dq3WBY0rTdtrckDDcKZfx4VhxE

1. Year in, year out
+ visuel avec dégustation avec le nez

2. Splash the mash
+ visuel de la machine

3. Not aged one bit
+ vidéo

Merci!

**Comment by WamiConcept** [comment]
@marieharder il n'était pas prévu d'avoir de vidéo directement visible dans le carousel. 
En plus c'est pas du Youtube.

**Comment by marieharder** [comment]
coucou @WamiConcept 
je l'avais demandé au début du projet :/
en revanche en effet le client avait demandé à ce que les vidéos soient hebergées sur YT
je lui demande quel contenu il souhaite mettre à la place

**Comment by WamiConcept** [comment]
C'est ok pour les visuels manquant. On attend la vidéo du coup.

**Comment by marieharder** [comment]
hello @WamiConcept 
Le voici on a une photo au final : 
https://drive.google.com/drive/folders/1SFion2Dq3WBY0rTdtrckDDcKZfx4VhxE
(photo nommée Older Dugga wide)

**Comment by enzo-wami** [comment]
l'image est en place
