### ISSUE TITLE
ALL / Food pairing section - ajout lien + PDF

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#27]
Hello @WamiConcept 
Au niveau de la section food pairing, il faudrait ajouter un lien + un PDF qui s'ouvre dans un nouvel onglet. 

> Le PDF est ici : https://drive.google.com/drive/folders/1SFion2Dq3WBY0rTdtrckDDcKZfx4VhxE
J'ai demandé la version Allemande aussi.

> Le texte à ajouter est : "Discover the impossibly balanced recipe"
> il faut le mettre juste en dessous du paragraphe A Balanced Diet (cf screenshot), en termes de style tu peux le traiter comme le CTA "Join Ardbeg Committe..." (cf screenshot)

<img width="1112" alt="Capture d’écran 2019-08-27 à 16 56 42" src="https://user-images.githubusercontent.com/37293165/63782470-ba4d2b00-c8eb-11e9-94e5-7081d12b2d94.png">

<img width="416" alt="Capture d’écran 2019-08-27 à 16 57 52" src="https://user-images.githubusercontent.com/37293165/63782705-144df080-c8ec-11e9-97bb-909b19876332.png">

**Comment by WamiConcept** [comment]
En place

**Comment by marieharder** [comment]
Hello @WamiConcept 
Il faudrait mettre le CTA en-dessous de la vidéo sur mobile only et l'aligner sur le texte et non sur la vidéo

![image015 (1)](https://user-images.githubusercontent.com/37293165/63932876-63b12f80-ca58-11e9-9748-e963180391c8.png)

**Comment by enzo-wami** [comment]
On ne peut pas changer l'emplacement de la vidéo en mobile en sachant qu'en desk la vidéo reste après le cta. En revanche j'ai corrigé le problème d'alignement
