### ISSUE TITLE
MOBILE - iPhone 8 - iOS 12.4.1 - Safari & Chrome / Tasting notes

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#28]
Hello @WamiConcept @enzo
On a un soucis d'affichage du "+" et de la légende sur le caillou

![image005 (1)](https://user-images.githubusercontent.com/37293165/63928072-3d3ac680-ca4f-11e9-907f-f5a680d25fcb.png)

**Comment by enzo-wami** [comment]
C'est corrigé
