### ISSUE TITLE
ALL - coquilles textes

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#29]
Hello @WamiConcept 
Il y a des coquilles sur les mots suivants : 
- Chilli 
- subtlety

![image009](https://user-images.githubusercontent.com/37293165/63928193-74a97300-ca4f-11e9-944c-9413aeea0d93.png)
![image007](https://user-images.githubusercontent.com/37293165/63928195-74a97300-ca4f-11e9-947e-ea336cc0a6a6.png)

**Comment by WamiConcept** [comment]
Corrigé
