### ISSUE TITLE
MOBILE - la bouteille qui rentre dans la boîte

### ISSUE THREAD

**Issue by matildeq** [matildeq/Ardbeg---Traigh-Bhan#3]
Hello,
Juste avant que la bouteille rentre dans la boîte il y a un petit souci de niveaux : 
la bouteille passe derrière les rochers. Est-ce que tu pourrais corriger cela stp ?
Merci,
Matilde

**Comment by antoinesimonwami** [comment]
C'est corrigé en preprod !

**Comment by matildeq** [comment]
Hello, 
C'est bon pour moi ! Merci !
