### ISSUE TITLE
ALL - Mobile - Chargement bouteille

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#30]
Hello @WamiConcept 
Le client me remonte que quand il charge la page pour la première fois et commence à scroller, la bouteille fait des sauts - est ce que tu peux checker si en termes de poids, l'asset de la bouteille est optimisé au mieux ?

**Comment by enzo-wami** [comment]
On a compressé l'image, elle est beaucoup moins lourde maintenant
