### ISSUE TITLE
ALL - Mobile - Ajout CTA Buy Now

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#31]
hello @WamiConcept 
Sur mobile le client est un peu embêté car le bouton Buy Now n'apparaît que tout en bas de la page. Il nous avait demandé d'avoir un bouton sticky comme sur desktop mais on lui avait dit non !

Du coup, il demande s'il serait possible d'ajouter sur mobile uniquement un autre CTA Buy Now en haut de la page, au dessus ou en dessous du premier paragraphe mais je pense que c'est quand même mieux en dessous ?

![image021](https://user-images.githubusercontent.com/37293165/63928606-22b51d00-ca50-11e9-81bd-e47927dca4ab.png)

**Comment by enzo-wami** [comment]
C'est fait, je l'ai ajouté en dessous des paragraphes
