### ISSUE TITLE
ALL - Phrase à mettre en gras

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#32]
Hello @WamiConcept @enzo
Il faudrait mettre la phrase suivante en gras : 
**Inspired by various distinguishing features around the Distillery, batch codes will change with each release.**

Elle se trouve dans le paragraphe sous l'otarie. 

![image022](https://user-images.githubusercontent.com/37293165/63929098-272e0580-ca51-11e9-9767-4f7539b2d462.png)

**Comment by WamiConcept** [comment]
C'est ok

**Comment by marieharder** [comment]
merci @WamiConcept 
tu peux aussi mettre la phrase en gras sur la version DE stp ?
c'est cella là : 
Es ist inspiriert von der Destillerie und der Umgebung, die von Ardbeg-Besuchern sicher leicht zu finden sein werden.

**Comment by WamiConcept** [comment]
C ok
