### ISSUE TITLE
ALL - Mobile - Alignement paragraphe The Ardbeg Committee

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#33]
Hello @WamiConcept 
Sur mobile, le paragraphe "The Ardbeg Committee" devrait être aligné sur le texte et non sur la vidéo (cf. screenshot maquette ci-dessous). 

<img width="249" alt="Capture d’écran 2019-08-29 à 12 29 05" src="https://user-images.githubusercontent.com/37293165/63933171-ffdb3680-ca58-11e9-8396-eb28281e4af3.png">

**Comment by enzo-wami** [comment]
C'est corrigé
