### ISSUE TITLE
ALL - Mobile - Titre dernière section "As a matter of Fact" + légendes

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#34]
Hello @WamiConcept 
Au niveau du titre de la dernière section sur mobile, il faudrait : 

1/ Revoir la taille de typo 
- "As a matter of fact" --> à caler sur la taille du titre "The Ardbeg Committee" dans le paragraphe juste au dessus
- phrase "See for...." --> à caler sur la taille de typo des paragraphes

2/ Revoir le positionnement 
- il faudrait que ce titre soit plus proche du contenu
- possible de le caler sur le côté gauche du contenu juste en dessous ? 

Au niveau des légendes de la dernière section sur mobile, il faudrait : 

3/ Mettre le même interletrage / interlignage que sur le reste de la page (les lettres de ces légendes sont plus espacées que celles des autres paragraphes sur la page)

**Comment by marieharder** [comment]
+ harmoniser aussi cela sur desktop :)

**Comment by enzo-wami** [comment]
C'est corrigé
