### ISSUE TITLE
ALL - version EN - Coquilles textes 2

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#35]
Hello @WamiConcept 
Petites coquilles à corriger sur les textes version EN.
Les modifs à faire sont highlightées en gras.

1. 1st paragraph - "Produced in small batches **to be** released every year..."

2. In "Especially Rare" section, beside seal image - "Inspired by **various distinguishing features around the Distillery**, batch codes will change with each release.”

3. In "The Batch Code" section, amend the actual batch code to match label - "TB/01-15.03.00/**19**.MH"

4. In the same section - "Join **the** Ardbeg **Committee** to be informed..."
 + mettre le lien suivant : https://shop.ardbeg.com/en-gb/register?returnUrl=https://www.ardbeg.com/en-gb

5. In the final Ardbeg Committee section - "Nineteen years on, while times have changed, **the Committee** remains"

6. In the same section - "To find out about the next Ardbeg Traigh Bhan release **you'll need to be part of the Committee**. So if..." --> enlever "in order" au début

**Comment by WamiConcept** [comment]
C'est ok
