### ISSUE TITLE
ALL - version DE - coquilles textes

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#36]
Hello @WamiConcept 
Quelques questions sur la version DE - highlightées ci-dessous en gras.

1. First paragraph - "der für seinen „singende**n** Sand“ bekannt ist.

2. Amend batch code to match label - "TB/01-15.03.00/19.MH" - same as en-gb

3. In Batch Code section - "aus der Brennblase lief. **In einem Jahr**, als der Millennium"

4. Final Das Ardbeg Committee section; 1st paragraph - "Damals kannten wir in der Destillerie noch alle Committee Mitglieder beim **Namen und es** erreichten uns regelmäßig Faxe von einigen!

5.  CTA Ardbeg Committee - "**DEM COMMITTEE BEITRETEN**"

6. Carousel images intro sentence - "**Erlebt bedeutsame Momente** bei Ardbeg, als diese Abfüllung zum ersten Mal destilliert wurde."

7. Jahr ein, Jahr aus caption - "Um es nachzuvollziehen, **entkorkt doch** einfach eine eigene Flasche… "

8. Dugga caption - "**Dugga, Ardbegs Warehouse-Chef**, war von Anfang an in der Destillerie..."

Merci !

**Comment by WamiConcept** [comment]
C'est ok

**Comment by marieharder** [comment]
@WamiConcept 
Le point 5 n'est pas OK il manque un "n" à BEITRETEN

**Comment by WamiConcept** [comment]
C'est ok
