### ISSUE TITLE
ALL - pack bouteille

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#37]
Hello @WamiConcept @antoinesimonwami 
Le client me remonte que le pack de la bouteille en bas de la page est un peu flou / pas très net.. est ce qu'on peut optimiser ça ?

**Comment by antoinesimonwami** [comment]
@WamiConcept j'ai retouché le packaging en local, il est bon à être poussé

**Comment by WamiConcept** [comment]
C push

**Comment by antoinesimonwami** [comment]
Je vois pas la diff, tu es certain?

**Comment by WamiConcept** [comment]
Oué, c le cache

**Comment by marieharder** [comment]
bcp mieux merci ! 
@antoinesimonwami
