### ISSUE TITLE
ALL - food pairing video link

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#39]
Hello @WamiConcept 
Voici le lien de la vidéo à intégrer au niveau de la section food pairing.

Link:
https://www.youtube.com/watch?v=IwDnwqJ3d8M

Embed code:
<iframe width="560" height="315" src="https://www.youtube.com/embed/IwDnwqJ3d8M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by WamiConcept** [comment]
C'est fait
