### ISSUE TITLE
MOBILE - Shortie

### ISSUE THREAD

**Issue by matildeq** [matildeq/Ardbeg---Traigh-Bhan#4]
Hello,
Tout en bas de la page il y a Shortie qui est très très petit, est-ce qu'on peut le mettre un peu plus grand pls ?
Merci beaucoup,
Matilde

**Comment by antoinesimonwami** [comment]
C'est corrigé en preprod !

**Comment by matildeq** [comment]
Hello, 
C'est bon pour moi ! Merci !
