### ISSUE TITLE
ALL - Lien sur CTA Join the Committe

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#40]
Hello @WamiConcept 
Il faut mettre les liens suivants sur les 2 CTAs Committe sur chaque page : 

EN 
> https://shop.ardbeg.com/en-gb/register?returnUrl=https://www.ardbeg.com/en-gb

DE
> https://shop.ardbeg.com/de-de/register?returnUrl=https://www.ardbeg.com/de-de

**Comment by WamiConcept** [comment]
C'est en place
