### ISSUE TITLE
ALL - EN version - CTA Committee

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#41]
Hello @WamiConcept @antoinesimonwami 

Il faut ajouter un "The" devant "Committee" sur le CTA ici

<img width="735" alt="Capture d’écran 2019-09-02 à 11 27 18" src="https://user-images.githubusercontent.com/37293165/64104534-ae8eb800-cd74-11e9-9d94-3f2c2cb108fe.png">

**Comment by WamiConcept** [comment]
En place
