### ISSUE TITLE
ALL - video food pairing - preview

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#42]
Hello @WamiConcept @antoinesimonwami 
Pour la video food pairing, il faudrait MAJ le visuel de preview, qui n'a pas été changer
--> utiliser une image extraite de la vidéo

**Comment by WamiConcept** [comment]
Il faut nous dire laquelle pour le preview pour éviter de le faire 5 fois. Merci !

**Comment by marieharder** [comment]
@WamiConcept la première frame please
<img width="1190" alt="Capture d’écran 2019-09-02 à 11 42 58" src="https://user-images.githubusercontent.com/37293165/64107743-7a6ac580-cd7b-11e9-9a4e-9f91b5c74449.png">

**Comment by WamiConcept** [comment]
Il faut mettre un traitement dessus pour que ca s'intègre par rapport à la créa. Qui avait fait le truc d'avant ?

**Comment by marieharder** [comment]
c'était l'autre agence...
océ est off et au vu des timings serrés, est ce que @antoinesimonwami peut nous bidouiller qqch ?
@WamiConcept

**Comment by WamiConcept** [comment]
C'est ok
