### ISSUE TITLE
ALL - DE version - CTA PDF recette

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#43]
Hello @WamiConcept @antoinesimonwami 
Sur le CTA de la recette sur la version allemande il faut rajouter cette mention entre parenthèses
(ENGLISCH)

On a donc le CTA suivant =
EIN UNMÖGLICH AUSGEWOGENES REZEPT (ENGLISCH)

**Comment by WamiConcept** [comment]
En place
