### ISSUE TITLE
ALL - Safari gros bug

### ISSUE THREAD

**Issue by matildeq** [matildeq/Ardbeg---Traigh-Bhan#5]
Hello @antoinesimonwami 
Nous avons remarqué que sur safari la page ne marche pas du tout 😱
Tu peux regarder stp ? 
Merci !
Matilde

**Comment by antoinesimonwami** [comment]
Hello @matildeq,
chez moi tout se passe bien sur Safari (12.0.1), est-ce que tu as vidé tes caches?
Si le problème persiste, tu pourrais préciser la nature du/des problèmes rencontrés + mettre des captures?

Merci :)
Antoine

**Comment by antoinesimonwami** [comment]
Testé sur Safari 11.1.1 également, tout est ok

**Comment by matildeq** [comment]
Hello @antoinesimonwami 
Là en effet je vois plus le gros souci d'hier ! peut-être une histoire de cache effectivement.. Par contre j'ai encore un souci sur le bas de page qui est... infini ! Après Shortie la page continue et continue vers le bas. Je suis avec une version 12.1.2
Tu peux vérifier si c'est pareil pour toi ? 
Merci

**Comment by antoinesimonwami** [comment]
Hello @matildeq,
en effet j'avais remarqué ce problème, mais rien sur le site n'explique ce comportement :
lorsque tu te trouve en bas de la page, dans la partie "scroll infinie", et que tu redimensionne(même un tout petit peu) ton navigateur, alors il va recalculer la hauteur de la page.

Je n'explique pas ce comportement, on dirait que ça vient du navigateur...
Je continu à regarder, mais je ne te promet rien (tu me connais :) )

**Comment by marieharder** [comment]
@antoinesimonwami @WamiConcept 
Hello, des news sur ce ticket ? :)

**Comment by antoinesimonwami** [comment]
Oui on a trouvé la solution, ça devrait fonctionner au prochain push sur la preprod

**Comment by antoinesimonwami** [comment]
Hello @marieharder,
ce problème est corrigé en preprod :)
