### ISSUE TITLE
MOBILE - Taille patounes

### ISSUE THREAD

**Issue by marieharder** [matildeq/Ardbeg---Traigh-Bhan#6]
Hello @antoinesimonwami 
Sur mobile, il faudrait refaire une passe sur les patounes pour : 
- harmoniser leur tailles (globalement c'est très petit, tu peux les grossir !)
- les rendre plus visibles (il y a moins de traces de pas sur mobile et souvent il y en a que 3-4, possible d'en mettre plus à la suite ?) --> notamment juste au dessus du titre Traign Bhan

**Comment by antoinesimonwami** [comment]
C'est bon, corrigé en preprod :)

**Comment by matildeq** [comment]
J'attends de voir que le souci du backgroud se clean avant de valider. ^^
