### ISSUE TITLE
CONTENT TO ADD 

### ISSUE THREAD

**Issue by matildeq** [matildeq/Ardbeg---Traigh-Bhan#7]
Hello @antoinesimonwami @WamiConcept 
Le client vient de parler à sa boss, et ils sont très heureux de la page !! Bravo !
Cependant il aimerait ajouter/ modifier quelques petits éléments : 

1. Est-ce que c'est possible d'ajouter une petite image de Shortie juste en dessous du premier rocher ? Cela pourra donner un peu plus de contextes au petites pattes qu'on croisera plus tard. 
![image](https://user-images.githubusercontent.com/28559173/63528519-66190400-c503-11e9-81fa-46c99a7c7ab9.png)
J'ai une belle image de Shortie (déjà détourée) dans ce PSD > https://drive.google.com/file/d/1MPCsCKYYXh32rhW-7FjsuMuPuRA5jK21/view?usp=sharing

2. Ils trouvent certains moments un petits peu vides, est-ce qu'on peut donc ajouter un peu de pattes de shortie ? Par exemple ici :
![image (1)](https://user-images.githubusercontent.com/28559173/63528646-9791cf80-c503-11e9-98af-32ccf6e5c8ba.png)
Et peut-être un peu ailleurs aussi. L'idée c'est qu'il faut pas mettre des pattes du chien chaque fois qu'il y a un trou blanc, mais juste en ajouter un peu. :) 

3. dernier point, est-ce qu'on peut adoucir le bord de la photo de la plage ? Il aimerait avoir un "softer bord", peut-être faire un petit effet de fondu ? 
![image (2)](https://user-images.githubusercontent.com/28559173/63528830-f1929500-c503-11e9-8a4e-9e027cd48c45.png)

Dis-moi si t'as besoin d'Océane pour quelque chose. :) 
Merci beaucoup !
Matilde

**Comment by antoinesimonwami** [comment]
1 - Chien ajouté
2 - Pattounes OK sur preprod
3 - Bords de l'image : on a pas touché comme vu avec Caroline, en revanche l'image est passée en N&B

**Comment by marieharder** [comment]
coucou @antoinesimonwami @WamiConcept 
Le client est satisfait des pattounes qui ont été ajoutées. Il trouve qu'elles sont juste un peu trop effacées / claires et que du coup par moment on ne le voit pas bien. 
Est ce que tu peux les foncer un peu ? @antoinesimonwami

**Comment by WamiConcept** [comment]
@marieharder ca demande a refaire toute les images ... :s ! La lisibilité est bien non ?

**Comment by marieharder** [comment]
shit ca te prendrait cb de temps ? 
@WamiConcept

**Comment by WamiConcept** [comment]
@antoinesimonwami ?

**Comment by antoinesimonwami** [comment]
Plus ou moins 1h

**Comment by marieharder** [comment]
@antoinesimonwami je pense qu'on va pas y couper..... mais je demande
au pire tu peux t'en occuper lundi matin ?

**Comment by antoinesimonwami** [comment]
oui je fais ça lundi matin :)

**Comment by marieharder** [comment]
@antoinesimonwami ok cool !
tu me dis dès que c'est good ? si on peut avoir la pp à jour en fin de matinée ce serait zouper

**Comment by antoinesimonwami** [comment]
Hello @marieharder,
c'est fait en local, je te ping sur slack dès que c'est poussé en PP :)

**Comment by antoinesimonwami** [comment]
@marieharder Ok pour les pattounes en PP
