### ISSUE TITLE
MOBILE - background issue

### ISSUE THREAD

**Issue by matildeq** [matildeq/Ardbeg---Traigh-Bhan#8]
Hello @antoinesimonwami @WamiConcept 
J'ai un petit souci au niveau du background..
![IMG_6015](https://user-images.githubusercontent.com/28559173/63529641-471b7180-c505-11e9-9d2c-9ebfd4fff120.PNG)
Je suis sur Safari mobile, iphone 7
Merci !
Matilde

**Comment by enzo-wami** [comment]
C'est corrigé
