### ISSUE TITLE
PATTES SHORTIE

### ISSUE THREAD

**Issue by matildeq** [matildeq/Ardbeg---Traigh-Bhan#9]
Hello @antoinesimonwami @WamiConcept 
Est-ce qu'on peut revoir les pattes de Shortie dans 2 points pls ? 
1. en dessous de l'image il faudrait que les pattes rentrent un peu plus vers le milieu de la page 
2. on peut ajouter des pattes juste après le batch code ? 

 Merci !
Matilde

**Comment by antoinesimonwami** [comment]
#7
